#!/bin/bash

# Usage : ./build-tarball <version>
#   e.g.: ./build-tarball 0.0.2

#*
#*  The MIT License
#* 
#*  Copyright 2012 Georgios Migdos <cyberpython@gmail.com>.
#* 
#*  Permission is hereby granted, free of charge, to any person obtaining a copy
#*  of this software and associated documentation files (the "Software"), to deal
#*  in the Software without restriction, including without limitation the rights
#*  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#*  copies of the Software, and to permit persons to whom the Software is
#*  furnished to do so, subject to the following conditions:
#* 
#*  The above copyright notice and this permission notice shall be included in
#*  all copies or substantial portions of the Software.
#* 
#*  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#*  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#*  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#*  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#*  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#*  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#*  THE SOFTWARE.
#*

TARGET_DIR="glossa-interpreter-$1"

if [ -d binaries/$TARGET_DIR ]
then
    rm -rf binaries/$TARGET_DIR
fi

mkdir -p binaries/$TARGET_DIR
cp -R readme binaries/$TARGET_DIR
cp -R nbproject binaries/$TARGET_DIR
cp -R src binaries/$TARGET_DIR
cp build.sh binaries/$TARGET_DIR/build.sh
cp build.xml binaries/$TARGET_DIR/build.xml
cp build-linux.xml binaries/$TARGET_DIR/build-linux.xml
cp build-tarball binaries/$TARGET_DIR/build-tarball
cp glossa-interpreter binaries/$TARGET_DIR/glossa-interpreter
cp Makefile binaries/$TARGET_DIR/Makefile
cp manifest.mf binaries/$TARGET_DIR/manifest.mf
cp README.mkdn binaries/$TARGET_DIR/README.mkdn

cd binaries

if [ -f glossa-interpreter-$1-src.tar.gz ]
then
    rm -f glossa-interpreter-$1-src.tar.gz
fi

tar -cvzf glossa-interpreter-$1.tar.gz $TARGET_DIR

rm -rf $TARGET_DIR

if [ $# -gt 0 ]
then

    if [ -f glossa-interpreter-src.tgz ]
    then
        rm -f glossa-interpreter-src.tgz
    fi

    cp glossa-interpreter-$1.tar.gz glossa-interpreter-src.tar.gz

fi

cd ../

