/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package glossa;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    // TODO: Add unit tests
}
