/*
 *  The MIT License
 * 
 *  Copyright 2010 Georgios Migdos <cyberpython@gmail.com>.
 * 
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 * 
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  THE SOFTWARE.
 */

/*
 * InterpreterMessagesListCellRenderer.java
 *
 * Created on Nov 9, 2010, 3:31:17 PM
 */

package glossa.ui.gui.io;

import glossa.messages.ErrorMessage;
import glossa.messages.WarningMessage;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Georgios Migdos <cyberpython@gmail.com>
 */
public class InterpreterMessagesListCellRenderer extends javax.swing.JPanel implements ListCellRenderer{

    Font defaultFont;
    Font errorFont;
    Font warningFont;
    Color defaultFg;
    Color errorFg;
    Color warningFg;

    Color normalBg;
    Color selectedBg;

    /** Creates new form InterpreterMessagesListCellRenderer */
    public InterpreterMessagesListCellRenderer() {
        initComponents();
        this.defaultFont = jLabel1.getFont();
        this.errorFont = defaultFont.deriveFont(Font.BOLD);
        this.warningFont = defaultFont.deriveFont(Font.ITALIC);
        this.defaultFg = Color.BLACK;
        this.errorFg = new Color(148, 65, 41);
        this.warningFg = new Color(41, 148, 81);
        this.normalBg = Color.WHITE;
        this.selectedBg = new Color(183, 203, 229);
    }

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

        jLabel1.setText("");
        if(value instanceof ErrorMessage){
            ErrorMessage error = (ErrorMessage) value;
            jLabel1.setFont(errorFont);
            jLabel1.setForeground(errorFg);
            jLabel1.setText("Σφάλμα (Γραμμή "+error.getPoint().x+", Στήλη "+(error.getPoint().y+1)+"): "+error.getMsg());
        }else if(value instanceof WarningMessage){
            WarningMessage warning = (WarningMessage) value;
            jLabel1.setFont(warningFont);
            jLabel1.setForeground(warningFg);
            jLabel1.setText("Προειδοποίηση (Γραμμή "+warning.getPoint().x+", Στήλη "+(warning.getPoint().y+1)+"): "+warning.getMsg());
        }else if(value instanceof String){
            String msg = (String) value;
            jLabel1.setFont(defaultFont);
            jLabel1.setForeground(defaultFg);
            jLabel1.setText(msg);
        }

        if(isSelected){
            setBackground(selectedBg);
        }else{
            setBackground(normalBg);
        }

        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(jLabel1.getFont());
        jLabel1.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
